#!/usr/bin/env python

from netmiko import ConnectHandler

SWT_6a = {
    'device_type': 'cisco_ios',
    'ip': '172.24.6.6',
    'username': 'cisco',
    'password': 'cisco',
}

SWT_5a = {
    'device_type': 'cisco_ios',
    'ip': '172.24.6.5',
    'username': 'cisco',
    'password': 'cisco',
}

with open('script') as f:
    lines = f.read().splitlines()
print (lines)

all_devices = [SWT_6a, SWT_5a]

for devices in all_devices:
    net_connect = ConnectHandler(**devices)
    output = net_connect.send_config_set(lines)
    print (output)
